version: '2.4'

services:
  mongo:
    image: mongo:4.2.6-bionic
    container_name: ancaphub_mongo
    ports:
      - '27017:27017'
    volumes:
      - ancaphub_mongo_data:/data/db
  postgres:
    image: postgres:15.0-alpine
    env_file:
      - ./.env
    container_name: ancaphub_postgres
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ancaphub_postgress_data:/data/db
  redis:
    image: redis:alpine
    container_name: ancaphub_redis
    ports:
      - '6379:6379'
    volumes:
      - ancaphub_redis_data:/data/db
  localstack:
    container_name: 'ancaphub_localstack'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - 'ancaphub_localstack_data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  ancaphub_postgress_data:
  ancaphub_localstack_data:
  ancaphub_mongo_data:
  ancaphub_redis_data:
