// Articles
export const FETCH_ALL_ARTICLES = "FETCH_ALL_ARTICLES"
export const FETCH_ARTICLE = "FETCH_ARTICLE"
export const SELECT_ARTICLES_CATEGORY = "SELECT_ARTICLES_CATEGORY"
export const SELECT_ARTICLES_ORDER = "SELECT_ARTICLES_ORDER"
export const SELECT_ARTICLES_PAGE = "SELECT_ARTICLES_PAGE"

// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const AUTH_ERROR = "AUTH_ERROR"
export const USER_LOADED = "USER_LOADED"
export const LOGOUT = "LOGOUT"

// Books
export const FETCH_ALL_BOOKS = "FETCH_ALL_BOOKS"
export const FETCH_BOOK = "FETCH_BOOK"
export const SELECT_BOOKS_CATEGORY = "SELECT_BOOKS_CATEGORY"
export const SELECT_BOOKS_ORDER = "SELECT_BOOKS_ORDER"
export const SELECT_BOOKS_PAGE = "SELECT_BOOKS_PAGE"

// Categories
export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES"
export const CATEGORY_ADDED = "CATEGORY_ADDED"
export const CATEGORIES_LOADING = "CATEGORIES_LOADING"

// User
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

// Errors
export const SET_ERRORS = "SET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"