// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const AUTH_ERROR = "AUTH_ERROR"
export const USER_LOADED = "USER_LOADED"
export const LOGOUT = "LOGOUT"
export const ADD_ITEM_TO_COLLECTION_SUCCESS = "ADD_ITEM_TO_COLLECTION_SUCCESS"
export const ADD_ITEM_TO_COLLECTION_FAIL = "ADD_ITEM_TO_COLLECTION_FAIL"
export const GET_CONTRIBUTIONS_SUCCESS = "GET_CONTRIBUTIONS_SUCCESS"
export const GET_CONTRIBUTIONS_FAIL = "GET_CONTRIBUTIONS_FAIL"
export const SAVE_ITEM_SUCCESS = "SAVE_ITEM_SUCCESS"
export const SAVE_ITEM_FAIL = "SAVE_ITEM_FAIL"
export const GET_SAVED_SUCCESS = "GET_SAVED_SUCCESS"
export const GET_SAVED_FAIL = "GET_SAVED_FAIL"

// Books
export const FETCH_ALL_BOOKS = "FETCH_ALL_BOOKS"
export const FETCH_BOOK = "FETCH_BOOK"
export const SELECT_BOOKS_CATEGORY = "SELECT_BOOKS_CATEGORY"
export const SELECT_BOOKS_ORDER = "SELECT_BOOKS_ORDER"
export const SELECT_BOOKS_PAGE = "SELECT_BOOKS_PAGE"
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS"

// Articles
export const FETCH_ALL_ARTICLES = "FETCH_ALL_ARTICLES"
export const FETCH_ARTICLE = "FETCH_ARTICLE"
export const SELECT_ARTICLES_CATEGORY = "SELECT_ARTICLES_CATEGORY"
export const SELECT_ARTICLES_ORDER = "SELECT_ARTICLES_ORDER"
export const SELECT_ARTICLES_PAGE = "SELECT_ARTICLES_PAGE"
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS"

// Videos
export const FETCH_ALL_VIDEOS = "FETCH_ALL_VIDEOS"
export const FETCH_VIDEO = "FETCH_VIDEO"
export const SELECT_VIDEOS_CATEGORY = "SELECT_VIDEOS_CATEGORY"
export const SELECT_VIDEOS_ORDER = "SELECT_VIDEOS_ORDER"
export const SELECT_VIDEOS_PAGE = "SELECT_VIDEOS_PAGE"
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS"

// Categories
export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES"
export const CATEGORY_ADDED = "CATEGORY_ADDED"
export const CATEGORIES_LOADING = "CATEGORIES_LOADING"

// User
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL"
export const GET_USER_FOLLOWERS_SUCCESS = "GET_USER_FOLLOWERS_SUCCESS"
export const GET_USER_FOLLOWERS_FAIL = "GET_USER_FOLLOWERS_FAIL"
export const GET_USER_COLLECTION_SUCCESS = "GET_USER_COLLECTION_SUCCESS"
export const GET_USER_COLLECTION_FAIL = "GET_USER_COLLECTION_FAIL"

// Posts
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const LOAD_USER_POSTS_SUCCESS = "LOAD_USER_POSTS_SUCCESS"
export const UPDATE_LIKES_SUCCESS = "UPDATE_LIKES_SUCCESS"
export const UPDATE_LIKES_ERROR = "UPDATE_LIKES_ERROR"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_ERROR = "DELETE_POST_ERROR"
export const LOAD_USER_FEED_SUCCESS = "LOAD_USER_FEED_SUCCESS"

// Errors
export const SET_ALERTS = "SET_ALERTS"
export const CLEAR_ALERTS = "CLEAR_ALERTS"
export const SHOW_SNACK = "SHOW_SNACK"